### ISSUE TITLE
WebUI - Stopping a pending zone will not actually stop it

### ISSUE THREAD

**Issue by mbdroid** [sprinkler/rainmachine-web-ui#112]
Stopping a pending zone will in fact only set the duration to 00:00, but it remains in pending

Steps to reproduce:
* start two zones
* stop the pending one
 * the zone is not actually stopped; checking the android app, the zone appears as being "pending" with duration 00:00
 * stopping a pending zone will result in that zone being set a default watering duration of 00:00 (see [issue #111](https://github.com/sprinkler/rainmachine-web-ui/issues/111) for more details)

**Comment by nicupavel** [comment]
Yes, the zone is actually still pending because we keep it in queue so we can add it to waterlog (even if it's canceled). Solution would be to remove the zone from queue and write it to waterlog, and if zone is started again update the previously saved waterlog entry. 
For web ui a temporary fix would be to not show it if pending with remaining = 00:00.
