### ISSUE TITLE
WebUI - Program graphs are not shown in dashboard (even after they have ran)

### ISSUE THREAD

**Issue by alexmireav** [sprinkler/rainmachine-web-ui#99]
Connect to 10.1.10.155
- Notice that there are 8 programs created
- Notice in watering history that some of the programs have clearly ran
- Go to Dashboard
- There are no program graphs

**Comment by nicupavel** [comment]
Programs will show once the they are simulated, simulation happens after receiving new weather. It's possible that programs would run before simulation, in which case the values for the program are calculated instantly but only for current program run.

You can check this case by dailystats/details API call. If program is not there yet, it wasn't simulated.
Might be a good idea if we show on dashboard "Program X - not simulated yet"

**Comment by cdumitriu** [comment]
If this bug is specific to spk1 then it is worth mentioning that simulation is not available on this device. GET dailystats/details is a time expensive request(~10s ttfb). The only place where dailystats/details is required is for future days prediction for generic water need graph. This is a very expensive DB read intensive request and we prefer the plain dailystats api call which is more than ~2 times faster and returns all future data except simulation values which are not working anyway. The way that the past days effective watering graphs are calculated in the web ui is using this formula (saved = (100 - parseInt((zoneDurations.real/zoneDurations.user) * 100))); these values are contained in the GET watering/log call. We decided to remove the user program water need predictions for future and show only effective watering history for the past days.
